### ISSUE TITLE
Hi, add x86 compile options for development or testing?

### ISSUE THREAD

**Issue by dnybz** [ZRouter/ZRouter#32]
Hi!
I am very interested in the ZRouter project, can you add x86 compile options for development or testing?

    thx  :)

**Comment by yamori813** [comment]
Hi

ZRouter have i386 setting already. Soekris/4501 device is use it. But I don't try to build it. May be can build.

**Comment by dnybz** [comment]
Thx !  I try to compile it. :)

**Comment by rayddteam** [comment]
IIRC, Soekris/4501 were never tested.

**Comment by dnybz** [comment]
I am use this config, compile failed
# make TARGET_PAIR=Soekris/4501 FREEBSD_SRC_TREE=/opt/ZRouter/freebsd_base_11.2.0 


/opt/ZRouter/freebsd_base_11.2.0/sys/sys/time.h:519:10: error: 'time.h' file not found with <angled> include; use "quotes" instead
#include <time.h>
         ^~~~~~~~
         "time.h"
In file included from /opt/ZRouter/freebsd_base_11.2.0/sys/geom/eli/g_eli_hmac.c:36:
/opt/ZRouter/freebsd_base_11.2.0/stand/libsa/stand.h:70:10: fatal error: 'string.h' file not found
#include <string.h>
         ^~~~~~~~~~
2 errors generated.
*** Error code 1

Stop.
make[4]: stopped in /opt/ZRouter/freebsd_base_11.2.0/stand/geli
*** Error code 1

Stop.
make[3]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.
make[2]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.
make[1]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.

**Comment by yamori813** [comment]
I think this is FreeBSD cross compile problem. Not ZRouter issue.

**Comment by dnybz** [comment]
The original error is like this.

===> stand/i386/btx (all)
===> stand/i386/btx/btx (all)
===> stand/i386/btx/btxldr (all)
===> stand/i386/btx/lib (all)
===> stand/i386/pmbr (all)
===> stand/i386/gptboot (all)
ld -static -N --gc-sections -Ttext 0x0 -o gptboot.out /usr/obj//opt/ZRouter/tmp//i386.i386/opt/ZRouter/freebsd_base_11.2.0/stand/i386/btx/lib/crt0.o gptboot.o sio.o crc32.o drv.o cons.o /usr/obj//opt/ZRouter/tmp//i386.i386/opt/ZRouter/freebsd_base_11.2.0/stand/geli/libgeliboot.a /usr/obj//opt/ZRouter/tmp//i386.i386/opt/ZRouter/freebsd_base_11.2.0/stand/libsa/libsa.a
ld: /usr/obj//opt/ZRouter/tmp//i386.i386/opt/ZRouter/freebsd_base_11.2.0/stand/geli/libgeliboot.a: No such file: No such file or directory
*** Error code 1

Stop.
make[4]: stopped in /opt/ZRouter/freebsd_base_11.2.0/stand/i386/gptboot
*** Error code 1

Stop.
make[3]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.
make[2]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.
make[1]: stopped in /opt/ZRouter/freebsd_base_11.2.0
*** Error code 1

Stop.
make: stopped in /opt/ZRouter

I edited the file socs/Intel/i386/soc.mk
Added “stand/geli” compile option

WORLD_SUBDIRS+=                 \
        stand/i386/btx  \
        stand/i386/pmbr \
        stand/geli \
        stand/i386/gptboot

**Comment by yamori813** [comment]
I seem cause of WORLD_SUBDIRS in socs/Intel/i386/soc.mk. Please try comment out this setting.

**Comment by dnybz** [comment]
Step 1: I edit the soc.mk file and save it

root@freebsd_dev:/ # vi /opt/ZRouter/socs/Intel/i386/soc.mk

#WORLD_SUBDIRS+=                        \
#       stand/i386/btx  \
#       stand/i386/pmbr        \
#       stand/libsa \
#       stand/i386/gptboot


root@freebsd_dev:/ # vi /opt/ZRouter/boards/Soekris/4501/board.mk

NEW_IMAGE_TYPE=split_kernel_rootfs => NEW_IMAGE_TYPE=zimage

Step 2: recompile ZRouter
root@freebsd_dev:/opt/ZRouter # make TARGET_PAIR=Soekris/4501 FREEBSD_SRC_TREE=/opt/ZRouter/freebsd_base_11.2.0

===> /../../..//opt/ZRouter/target/sbin/cdevd (all)
===> /../../..//opt/ZRouter/target/usr.bin/hex2bin (all)
===> /../../..//opt/ZRouter/profiles/SMALL_ (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua/ (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//lua (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luadns (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luaexpat (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luaposix (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasocket (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasocket/mime (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasocket/socket (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasocket/unix (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasysctl (all)
===> /../../..//opt/ZRouter/target/usr.bin/lua//luasyslog (all)
===> /../../..//opt/ZRouter/target/lib/libdhcp (all)
===> /../../..//opt/ZRouter/target/sbin/dhcpd (all)
===> /../../..//opt/ZRouter/target/sbin/dhclient (all)
===> /../../..//opt/ZRouter/target/sbin/dhcrelay (all)
===> /../../..//opt/ZRouter/target/sbin/dnsmasq (all)
===> /../../..//opt/ZRouter/target/lib/liblzo2 (all)
===> /../../..//opt/ZRouter/target/sbin/openvpn (all)

--------------------------------------------------------------
>>> World build completed on Wed Feb 27 06:51:11 CST 2019
--------------------------------------------------------------
rm -rf /usr/obj//opt/ZRouter/x86_i386_rootfs
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs/var/empty: Operation not permitted
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs/var: Directory not empty
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs: Directory not empty
*** Error code 1

Stop.
make: stopped in /opt/ZRouter

Step 3: Compile completed, but did not find the generated image file

root@freebsd_dev:/ # ll /usr/obj/opt/ZRouter/
total 16
drwxr-xr-x  2 root  wheel  512 Feb 27 06:04 conf/
drwxr-xr-x  3 root  wheel  512 Feb 27 06:07 ports/
drwxr-xr-x  3 root  wheel  512 Feb 26 08:17 tmp/
drwxr-xr-x  3 root  wheel  512 Feb 27 06:42 x86_i386_rootfs/

**Comment by dnybz** [comment]
rm -rf /usr/obj//opt/ZRouter/x86_i386_rootfs
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs/var/empty: Operation not permitted
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs/var: Directory not empty
rm: /usr/obj//opt/ZRouter/x86_i386_rootfs: Directory not empty

======================================================
root@freebsd_dev:/ # vi /usr/obj/opt/ZRouter/Makefile

find 545 line add "find ${WORLDDESTDIR} -flags schg -exec chflags noschg {} \;"

rootfs-dir!
        find ${WORLDDESTDIR} -flags schg -exec chflags noschg {} \;
        rm -rf ${WORLDDESTDIR}

**Comment by dnybz** [comment]
===>  Installing for mpd5-5.8_10
--------> Done building  port ...
----> Ports dependencies build done ...
touch "/usr/obj//opt/ZRouter/x86_i386.zimage"

The compilation is now successful, but I can't start it with qemu "D:\Program Files\qemu\qemu-system-x86_64.exe" -m 2048 x86_i386.zimage

qemu boot message:

Boot failed: not a bootable disk

**Comment by rayddteam** [comment]
Hi Qiang Wang!

Booting of MIPS/ARM mostly looks like:
power up -> CPU call uboot at 0 address -> uboot load and call system kernel from kernel partition

Booting of i386/amd64 machine much complex:
power up -> CPU call BIOS at 0 address -> [x] BIOS load 0 block from selected drive ->
-> check if that block contains valid info about drive partitioning -> execute this block ->
-> code in block loads few blocks of selected (bootable) partition and execute ->
-> partition code search its FS inside to find loader(8) [y] -> loader load and execute kernel

We have prepared ZRouter.org to make image to much simple case for embedded systems use.
But not for i386 yet.
BTW, there is also UEFI way to boot i386/amd64, it's a bit simpler.

As I said before, Soekris is not tested, but it may use simple scheme like MIPS/ARM (because it is small embedded system). Other, standard ways to boot i386/amd64 not implemented yet.

If you like, I, and hope others, may help you to done it.

Thanks for you interest to project!

**Comment by dnybz** [comment]
Hi Aleksandr Rybalko!

I am very interested in ZRouter.
Because ZRouter is based on FreeBSD, not Linux.
Something like openwrt, I want to build an x86 ZRouter image that runs on my machine.

Thanks for you!  I hope add support for x86.

**Comment by rayddteam** [comment]
Let's select environment to run VM on.
qemu - because it can run other CPU types too?
- or -
bhyve - because it is native to FreeBSD?
There is also problem of CPU virtualization bits, so bhyve may not able to run on some VMs and some hosts.

**Comment by dnybz** [comment]
If ZRouter can run on a virtual machine,
Also a good choice.

**Comment by josla972** [comment]
With a big CF card could you just not run x86 FreeBSD as it is? Do you have size constraints?

**Comment by dnybz** [comment]
Running on x86, mainly for development and debugging, the size is best limited to 512MB
