### ISSUE TITLE
Shared object "libncursesw.so.8" not found, required by "libedit.so.7"

### ISSUE THREAD

**Issue by rayddteam** [ZRouter/ZRouter#9]
Found by: @josla972
Bootlog:
https://gist.github.com/rayddteam/ac8c1593aa9b79fc9fd55cd75ac959e2

**Comment by josla972** [comment]
Fix proposal:

diff --git a/profiles/SMALL_/profile.mk b/profiles/SMALL_/profile.mk
index f5d2a19..eb282fa 100644
--- a/profiles/SMALL_/profile.mk
+++ b/profiles/SMALL_/profile.mk
@@ -22,7 +22,7 @@ libthr \
 libufs \
 libutil \
 libz \
-ncurses/ncurses \
+ncurses/ncursesw \
 ncurses/form \
 ncurses/menu \
 ncurses/panel
